import { Briefcase, Car, ShoppingCart, CreditCard, TrendingUp, Users, CalendarDays, ListTodo, PieChart, StickyNote } from 'lucide-react';

export const AVAILABLE_MODULES = [
    {
        id: 'mobility',
        label: 'Movilidad',
        description: 'Registrá tus ingresos por Uber, Didi, Cabify y otros. Calculá cuánto ganás por hora y por kilómetro.',
        icon: Car,
        color: 'from-violet-600 to-indigo-600',
        iconBg: 'bg-violet-100',
        iconColor: 'text-violet-600',
        badge: 'Nuevo',
    },
    {
        id: 'supermarket',
        label: 'Supermercado',
        description: 'Gestioná tu lista de compras, registrá gastos del super y escaneá tickets para llevar el historial mensual.',
        icon: ShoppingCart,
        color: 'from-emerald-500 to-teal-600',
        iconBg: 'bg-emerald-100',
        iconColor: 'text-emerald-600',
        badge: null,
    },
    {
        id: 'cards',
        label: 'Tarjetas de Crédito',
        description: 'Administrá tus tarjetas, cargá resúmenes del mes (con IA), marcá pagos y visualizá tus cuotas pendientes.',
        icon: CreditCard,
        color: 'from-blue-600 to-indigo-600',
        iconBg: 'bg-blue-100',
        iconColor: 'text-blue-600',
        badge: null,
    },
    {
        id: 'savings',
        label: 'Ahorros e Inversiones',
        description: 'Gestioná tus metas de ahorro, registrá tus saldos y seguí el rendimiento de tus inversiones.',
        icon: TrendingUp,
        color: 'from-amber-500 to-orange-600',
        iconBg: 'bg-amber-100',
        iconColor: 'text-amber-600',
        badge: null,
    },
    {
        id: 'salary',
        label: 'Sueldo Mensual',
        description: 'Planificá cómo distribuir tu sueldo mes a mes. Configurá fuentes de ingreso, creá sobres por categoría y conectá tus gastos familiares.',
        icon: Briefcase,
        color: 'from-violet-600 to-indigo-600',
        iconBg: 'bg-violet-100',
        iconColor: 'text-violet-600',
        badge: 'Nuevo',
    },
    {
        id: 'household',
        label: 'Grupo Familiar y Reparto',
        description: 'Gestioná los miembros de tu hogar, sus sueldos y calculá el reparto proporcional de los gastos compartidos.',
        icon: Users,
        color: 'from-pink-500 to-rose-600',
        iconBg: 'bg-pink-100',
        iconColor: 'text-pink-600',
        badge: null,
    },
    {
        id: 'agenda',
        label: 'Agenda de Vencimientos',
        description: 'Calendario de servicios fijos, tarjetas de crédito y recordatorios de pagos.',
        icon: CalendarDays,
        color: 'from-cyan-500 to-blue-600',
        iconBg: 'bg-cyan-100',
        iconColor: 'text-cyan-600',
        badge: null,
    },
    {
        id: 'planner',
        label: 'Planificador Financiero',
        description: 'Organizá tu presupuesto mensual, definí objetivos y planificá tus compras (ferias, etc.).',
        icon: ListTodo,
        color: 'from-fuchsia-500 to-purple-600',
        iconBg: 'bg-fuchsia-100',
        iconColor: 'text-fuchsia-600',
        badge: null,
    },
    {
        id: 'stats',
        label: 'Estadísticas y Análisis',
        description: 'Visualizá gráficos detallados de tus finanzas y proyecciones a futuro.',
        icon: PieChart,
        color: 'from-indigo-500 to-blue-600',
        iconBg: 'bg-indigo-100',
        iconColor: 'text-indigo-600',
        badge: null,
    },
    {
        id: 'notes',
        label: 'Notas Rápidas',
        description: 'Post-it flotante para llevar una lista rápida de tareas pendientes (estilo Google Keep).',
        icon: StickyNote,
        color: 'from-yellow-400 to-amber-500',
        iconBg: 'bg-yellow-100',
        iconColor: 'text-yellow-600',
        badge: 'Nuevo',
    },
];
